export const DELETE_WORD = 'DELETE_WORD';
export const ADD_WORD = 'ADD_WORD';
export const FILTER_WORDS = 'FILTER_WORDS';
export const GLOBAL_SEARCH = 'GLOBAL_SEARCH';
export const UPDATE_GLOBAL_SEARCH_STRING = 'UPDATE_GLOBAL_SEARCH_STRING';
export const IS_LOADING = 'IS_LOADING';
export const INIT_STATE = 'INIT_STATE';
export const SHOW_TOASTR = 'SHOW_TOASTR';
